services:
    _defaults:
        autowire: true
        autoconfigure: true

    TotalCRM\AmoCRM\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Manager/'
            - '../../../src/EventListener/'
            - '../../../src/Token/'

    amo_crm.client:
        public: true
        class: TotalCRM\AmoCRM\DependencyInjection\AmoCRMClient
        arguments: ['@service_container']

    amo_crm.contact_manager:
        public: true
        class: TotalCRM\AmoCRM\Manager\ContactManager
        arguments: ["@amo_crm.client"]

    amo_crm.leads_manager:
        public: true
        class: TotalCRM\AmoCRM\Manager\LeadsManager
        arguments: ["@amo_crm.client"]

    amo_crm.redirect_exception_listener:
        public: true
        class: TotalCRM\AmoCRM\EventListener\RedirectExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    amo_crm.session_storage:
        public: true
        class: TotalCRM\AmoCRM\Token\SessionStorage
        arguments: ['@service_container']
